name: Release

on:
  push:
    tags:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'
    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        $ver = '${{ github.ref_name }}'
        dotnet build --no-restore -c Release --nologo -p:Version=$ver -p:FileVersion=$ver -p:AssemblyVersion=$ver'
    - name: Write version into manifest
      run: |
        $ver = '${{ github.ref_name }}'
        $path = './RoleplayingVoiceDalamud/bin/Release/net7.0/RoleplayingVoiceDalamud.json'
        $json = Get-Content -Raw $path | ConvertFrom-Json
        $json.AssemblyVersion = $ver
        $content = $json | ConvertTo-Json
       set-content -Path $path -Value $content
    - name: Packing Release
      run: |
        pushd publish_gtk
        7z a ../RoleplayingVoiceDalamud/bin/Release/net7.0/RoleplayingVoiceDalamud.zip publish
        popd
      shell: bash
    - name: Pushing Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: RoleplayingVoiceDalamud-${{ github.ref_name }}
          artifacts: "./RoleplayingVoiceDalamud/bin/Release/net7.0/*.zip"
          tag: ${{ github.ref_name }}
          #body: "Are you lost? This is no place to be in."
          omitBodyDuringUpdate: true
          allowUpdates: true
          replacesArtifacts: true
          #token: ${{ secrets.RELEASE_TOKEN }}
    - name: Write out repo.json
      run: |
        $ver = '${{ github.ref_name }}'
        $path = './repo.json'
        $json = Get-Content -Raw $path | ConvertFrom-Json
        $json[0].AssemblyVersion = $ver
        $json[0].TestingAssemblyVersion = $ver
        $json[0].DownloadLinkInstall = $json.DownloadLinkInstall -replace '[^/]+/RoleplayingVoiceDalamud.zip',"$ver/RoleplayingVoiceDalamud.zip"
        $json[0].DownloadLinkTesting = $json.DownloadLinkTesting -replace '[^/]+/RoleplayingVoiceDalamud.zip',"$ver/RoleplayingVoiceDalamud.zip"
        $json[0].DownloadLinkUpdate = $json.DownloadLinkUpdate -replace '[^/]+/RoleplayingVoiceDalamud.zip',"$ver/RoleplayingVoiceDalamud.zip"
        $content = $json | ConvertTo-Json -AsArray
        set-content -Path $path -Value $content

    - name: Commit repo.json
      run: |
        git config --global user.name "Actions User"
        git config --global user.email "actions@github.com"
        git fetch origin master
        git branch -f master ${{ github.sha }}
        git checkout master
        git add repo.json
        git commit -m "[CI] Updating repo.json for ${{ github.ref_name }}" || true
        git push origin master
